//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSApplicationWeb.WSPersonas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personas", Namespace="http://schemas.datacontract.org/2004/07/MiWS")]
    [System.SerializableAttribute()]
    public partial class Personas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoIdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoIdentificacion {
            get {
                return this.DocumentoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoIdentificacionField, value) != true)) {
                    this.DocumentoIdentificacionField = value;
                    this.RaisePropertyChanged("DocumentoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPersonas.IWSPersonas")]
    public interface IWSPersonas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/NuevaPersona", ReplyAction="http://tempuri.org/IWSPersonas/NuevaPersonaResponse")]
        int NuevaPersona(WSApplicationWeb.WSPersonas.Personas persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/NuevaPersona", ReplyAction="http://tempuri.org/IWSPersonas/NuevaPersonaResponse")]
        System.Threading.Tasks.Task<int> NuevaPersonaAsync(WSApplicationWeb.WSPersonas.Personas persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/EditarPersona", ReplyAction="http://tempuri.org/IWSPersonas/EditarPersonaResponse")]
        int EditarPersona(WSApplicationWeb.WSPersonas.Personas persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/EditarPersona", ReplyAction="http://tempuri.org/IWSPersonas/EditarPersonaResponse")]
        System.Threading.Tasks.Task<int> EditarPersonaAsync(WSApplicationWeb.WSPersonas.Personas persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/EliminarPersona", ReplyAction="http://tempuri.org/IWSPersonas/EliminarPersonaResponse")]
        int EliminarPersona(int idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/EliminarPersona", ReplyAction="http://tempuri.org/IWSPersonas/EliminarPersonaResponse")]
        System.Threading.Tasks.Task<int> EliminarPersonaAsync(int idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/buscarPersona", ReplyAction="http://tempuri.org/IWSPersonas/buscarPersonaResponse")]
        WSApplicationWeb.WSPersonas.Personas buscarPersona(int idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/buscarPersona", ReplyAction="http://tempuri.org/IWSPersonas/buscarPersonaResponse")]
        System.Threading.Tasks.Task<WSApplicationWeb.WSPersonas.Personas> buscarPersonaAsync(int idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/listarPersonas", ReplyAction="http://tempuri.org/IWSPersonas/listarPersonasResponse")]
        WSApplicationWeb.WSPersonas.Personas[] listarPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersonas/listarPersonas", ReplyAction="http://tempuri.org/IWSPersonas/listarPersonasResponse")]
        System.Threading.Tasks.Task<WSApplicationWeb.WSPersonas.Personas[]> listarPersonasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSPersonasChannel : WSApplicationWeb.WSPersonas.IWSPersonas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPersonasClient : System.ServiceModel.ClientBase<WSApplicationWeb.WSPersonas.IWSPersonas>, WSApplicationWeb.WSPersonas.IWSPersonas {
        
        public WSPersonasClient() {
        }
        
        public WSPersonasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPersonasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPersonasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NuevaPersona(WSApplicationWeb.WSPersonas.Personas persona) {
            return base.Channel.NuevaPersona(persona);
        }
        
        public System.Threading.Tasks.Task<int> NuevaPersonaAsync(WSApplicationWeb.WSPersonas.Personas persona) {
            return base.Channel.NuevaPersonaAsync(persona);
        }
        
        public int EditarPersona(WSApplicationWeb.WSPersonas.Personas persona) {
            return base.Channel.EditarPersona(persona);
        }
        
        public System.Threading.Tasks.Task<int> EditarPersonaAsync(WSApplicationWeb.WSPersonas.Personas persona) {
            return base.Channel.EditarPersonaAsync(persona);
        }
        
        public int EliminarPersona(int idPersona) {
            return base.Channel.EliminarPersona(idPersona);
        }
        
        public System.Threading.Tasks.Task<int> EliminarPersonaAsync(int idPersona) {
            return base.Channel.EliminarPersonaAsync(idPersona);
        }
        
        public WSApplicationWeb.WSPersonas.Personas buscarPersona(int idPersona) {
            return base.Channel.buscarPersona(idPersona);
        }
        
        public System.Threading.Tasks.Task<WSApplicationWeb.WSPersonas.Personas> buscarPersonaAsync(int idPersona) {
            return base.Channel.buscarPersonaAsync(idPersona);
        }
        
        public WSApplicationWeb.WSPersonas.Personas[] listarPersonas() {
            return base.Channel.listarPersonas();
        }
        
        public System.Threading.Tasks.Task<WSApplicationWeb.WSPersonas.Personas[]> listarPersonasAsync() {
            return base.Channel.listarPersonasAsync();
        }
    }
}
